### ISSUE TITLE
Error when try to view tags

### ISSUE THREAD

**Issue by pnkr** [coolcat-creations/plg_cccsocialmedia#11]
I have the latest version of cccsocialmedia.
When I view an article, if I click on a tag the following error occurs.

0
Argument 1 passed to plgSystemCccsocialmedia::getArticle() must be of the type int, array given, called in /plugins/system/cccsocialmedia/cccsocialmedia.php on line 129

I have tried it on various websites with joomla 4.3.0 and 4.3.1
On websites with version 4.2.8 it works fine.

**Comment by pnkr** [comment]
The issue is with this: $article        = $this->getArticle($input->get('id', 0, 'int'));

**Comment by coolcat-creations** [comment]
Hello, I fixed the issue in 2.0.1

**Comment by pnkr** [comment]
Thanks!!!
