### ISSUE TITLE
Error: Argument 1 passed <...>

### ISSUE THREAD

**Issue by Bill890** [coolcat-creations/plg_cccsocialmedia#12]
Hi,

I installed your plugin and in some top level menus I get this:

_Argument 1 passed to plgSystemCccsocialmedia::getArticle() must be of the type int, array given, called in /home/www/*** database name here *** / *** domain here ***/www/site/plugins/system/cccsocialmedia/cccsocialmedia.php on line 136_

***are there for my personal info to be hidden.

Is there something I can fix using notepad++?

**Comment by coolcat-creations** [comment]
Hello! I fixed the issue in the latest release
